// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package goclean

import (
	"github.com/prongbang/goclean/internal/app/api"
	"github.com/prongbang/goclean/internal/app/api/promotion"
	"github.com/prongbang/goclean/internal/app/api/swagger"
	"github.com/prongbang/goclean/internal/pkg/database"
)

// Injectors from wire.go:

func NewAPI(drivers database.Drivers) api.API {
	dataSource := promotion.NewDataSource(drivers)
	repository := promotion.NewRepository(dataSource)
	useCase := promotion.NewUseCase(repository)
	handler := promotion.NewHandler(useCase)
	router := promotion.NewRouter(handler)
	swaggerRouter := swagger.NewRouter()
	routers := api.NewRouters(router, swaggerRouter)
	apiAPI := api.New(routers)
	return apiAPI
}
